### ISSUE TITLE
hybrid mode problem

### ISSUE THREAD

**Issue by jamilservicos** [DigitalPandacoin/pandacoin#19]
I change for hybrid and stay "searching for peers"

hybrid mode dont work?

**Comment by jamilservicos** [comment]
send version message: version 70002, blocks=2000536, us=189.82.83.16:22445, them=75.128.183.25:22445, peer=75.128.183.25:22445
socket recv error  (104)
disconnecting node 75.128.183.25:22445
Disconnecting peer node. 
connect() failed after select(): Conexão recusada
connect() failed after select(): Não há rota para o host
connect() failed after select(): Não há rota para o host
connect() failed after select(): Conexão recusada
connect() failed after select(): Conexão recusada

**Comment by jamilservicos** [comment]
sync completed and autoclosed client.

"terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Abortado (imagem do núcleo gravada)"

When I try to reopen it appears
"Error loading blkindex.dat"

**Comment by DigitalPandacoin** [comment]
We recommend classic mode for now, however if you would like to use hybrid mode always start PandaBank with the command line option -clientmode=hybrid.

**Comment by jamilservicos** [comment]
Hybrid does not work, always have error during blockchain check, and it restart from scratch again.

**Comment by DigitalPandacoin** [comment]
This is resolved with our new chain automated swap upgrade and headers first fast sync by default.  Hybrid mode is deprecated.
